eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admineureka@localhost:9999/eureka/
spring:
  datasource:
    name: test
    url: jdbc:mysql://10.11.9.19/rayootech?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root 
    type : com.alibaba.druid.pool.DruidDataSource
    driver-class-name : com.mysql.cj.jdbc.Driver
    filters : stat
    maxActive : 20
    initialSize : 1
    maxWait : 60000
    minIdle : 1
    timeBetweenEvictionRunsMillis : 60000
    minEvictableIdleTimeMillis : 300000
    validationQuery : select 'x'
    testWhileIdle : true
    testOnBorrow : false
    testOnReturn : false
    poolPreparedStatements : true
    maxOpenPreparedStatements : 20      
feign:
  service:
    system: system
    project: project    

#eureka.client.serviceUrl.defaultZone=http://peer1:1111/eureka/,http://peer2:1112/eureka/    