server:
  port: 9999

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://admin:admineurek@localhost:${server.port}/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0
  instance:
    hostname: eureka-server1
security:
  user:
    name: admin 
    password: admineureka