server:
    port: 8006
application:
    version:1.0
    formatted-version:formatted-version.2.0

spring:
  datasource:
    name: river
    url: jdbc:mysql://10.11.9.19/rayootech?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root 
    type : com.alibaba.druid.pool.DruidDataSource
    driver-class-name : com.mysql.cj.jdbc.Driver
    filters : stat
    maxActive : 20
    initialSize : 1
    maxWait : 60000
    minIdle : 1
    timeBetweenEvictionRunsMillis : 60000
    minEvictableIdleTimeMillis : 300000
    validationQuery : select 'x'
    testWhileIdle : true
    testOnBorrow : false
    testOnReturn : false
    poolPreparedStatements : true
    maxOpenPreparedStatements : 20   
mybatis:
  typeAliasesPackage: com.rayootech.system.entity
  mapperLocations: classpath:/mapper/*.xml
  configLocation: classpath:/mybatis-config.xml
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admineureka@localhost:9999/eureka/
    instance:
      hostname: system
security:
  user:
    name: admin
    password: admin

